# Generated by Django 4.1.2 on 2022-10-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgarageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168)),
                ('isAdmin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.IntegerField()),
                ('password', models.CharField(max_length=168)),
            ],
        ),
    ]
