# Generated by Django 4.1.2 on 2022-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgarageapp', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutclass',
            name='enable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
