# Generated by Django 4.1.2 on 2022-10-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgarageapp', '0003_workoutclass_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=168)),
                ('classname', models.CharField(max_length=168)),
                ('grade', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
