# Generated by Django 4.1.2 on 2022-11-16 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitgarageapp', '0004_customreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitgarageapp.customuser')),
                ('workoutClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitgarageapp.workoutclass')),
            ],
        ),
    ]
