# Generated by Django 4.1.2 on 2022-11-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitgarageapp', '0005_booking'),
        ('fitgarageapp', '0006_alter_customuser_name'),
    ]

    operations = [
    ]
